### ISSUE TITLE
[Bug] AuthProvider invalid children types in React 18

### ISSUE THREAD

**Issue by Moshyfawn** [Forward-Software/react-auth#1]
### What happened?

# What happened
Using React 18, passing `children` into `AuthProvider` causes TS to complain.

# Additional Information about React 18
In React 18, the `React.FC` `props` type has changed
```ts
export declare function createAuth(): {
  AuthProvider: React.FC<AuthProviderProps>
}
```
## Before
```ts
interface FunctionComponent<P = {}> {
  (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null
}
```
## After
```ts
interface ForwardRefRenderFunction<T, P = {}> {
  (props: P, ref: ForwardedRef<T>): ReactElement | null
}
```
# Reproduction
Live reproduction environment: [codesanbox](https://codesandbox.io/s/pedantic-cache-lphlme?file=%2Ftype.ts%3A452-906)
# Personal Notes
There're 2 main ways to go about the React 18 functional component props with `children`:
- Put the `AuthProviderProps` inside `React.PropsWithChildren` first, then inside `React.FC`
```ts
export declare function createAuth(): {
  AuthProvider: React.FC<React.PropsWithChildren<AuthProviderProps>>
}
```
- Manually add the `children` prop type

I'm leaning more towards using the `React.PropsWithChildren` type.

Either way, feel free to ping me to add a PR, if you feel like it ;)

### What did you expect to happen?

No TS error when wrapping a component in `AuthProvider`

### Steps to reproduce the issue

- Install React 18 in a project _(make sure to have @types/react@^18 installed)_
```json
{
  "devDependencies": {
    "@types/react": "18.0.9"
  }
}
```
- Wrap a part of your app in `AuthProvider`
- See the TS error

### Version

v1.0.1

### What environment are you seeing the problem on?

ReactJS (specify Browser below)

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & AuthProviderProps'.ts(2559)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IronTony** [comment]
We are waiting for the release of React-Native 0.69 that will support React 18

**Comment by Moshyfawn** [comment]
I see your point. Fair enough!
